### ISSUE TITLE
How to get Dice so Nice to Work in Stream View

### ISSUE THREAD

**Issue by bluecollardm** [ardittristan/VTTStreamUtils#5]
I’ve turned on the dice so nice option in stream utilities module, but it doesn’t seem to work for me. Is there an issue with additional dice types from addon modules for dice so nice? I’m confused why it’s not populating for me. Thank you in advance! This option will definitely be a great one and will really improve many streams out there!

**Comment by ardittristan** [comment]
![image](https://user-images.githubusercontent.com/42787508/118847684-48daba80-b8ce-11eb-8308-0ee14f1ed46f.png)

Do you see this box? If you do and DSN doesn't work something is wrong and you could look if you can find any errors in console.
If you don't see the box, that means that either the stream client doesn't have the setting, or something is broken.
Did you enable the setting on the client browser or on the browser that opens /stream. because currently it should be done on the browser that opens /stream.
I will implement a way to push settings to /stream pages from a different client, but that will be in the future #4

**Comment by bluecollardm** [comment]
For more transparency, I'm running the game on Forge-VTT. As such, I am running my DM view as well as stream view in the same browser (Chrome). I do not see the box when I open the stream view.

**Comment by ardittristan** [comment]
ah, I'm using things that only work in 0.8 in the DsN widget, lemme see if I can fix it!

**Comment by bluecollardm** [comment]
![image](https://user-images.githubusercontent.com/83302261/119718176-3e23a680-be35-11eb-997e-b9b7e37180b3.png)
any solutions for this issue in the console? This appears to be stopping the dice from being rolled in the box now in 7.9 on the Forge.

**Comment by ardittristan** [comment]
figured issue, when combat tracker widget is disabled it doesn't load combat tracker compat (which it should since it kinda breaks the whole /stream view) will fix!
