### ISSUE TITLE
Getting the Dice Rolls as plain numbers

### ISSUE THREAD

**Issue by ZeroIchiro** [ardittristan/VTTStreamUtils#9]
Hey there,

is there a way to somehow get a simple mapping of player name and last dice roll?
For my overlay, I don't need the whole chat log, just the dice rolls.
Like:

Player A ......  12
Player B ......  22
Player C ......  19
Player D ......  18

and so on ...

Thanks in advance

**Comment by ZeroIchiro** [comment]
@ardittristan just a quick remark: Could you add a toggle switch to toggle between the current version (dice roll + modifier) and the sum (result of the equation)?

**Comment by ardittristan** [comment]
Do you mean one that toggles live without reloading the page?

**Comment by ZeroIchiro** [comment]
> Do you mean one that toggles live without reloading the page?

No, a live toggle is not necessary.

**Comment by ardittristan** [comment]
Sorry, I misread (been a while since I worked on this) though both were already existing options and you wanted to quickly switch between them.

As an answer, theoretically yes, but it would require a lot of work, currently I'm using a built-in variable that foundry has that supplies the last roll, but that only gives the total of the last roll, and not any other info. So that would require implementing a separate roll tracker.

**Comment by ZeroIchiro** [comment]
Okay, so, when I roll 1d20+5, there is no way I get the total result, and not something like "15+5"?

**Comment by ardittristan** [comment]
oh wait, I see what you mean now, I'll add it!

**Comment by ZeroIchiro** [comment]
Thank you very much :) 
P.S. Check your Paypal Inbox :) 💯
